# Generated by Django 4.0.4 on 2022-05-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_slot_slot_date_slot_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='avalible_slot',
            field=models.IntegerField(default=1),
        ),
    ]
