# Generated by Django 4.0.4 on 2022-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_alter_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('absent', 'Absent'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
