# Generated by Django 4.0.4 on 2022-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='weeks',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10),
        ),
    ]
