# Generated by Django 4.0.4 on 2022-05-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
